# Generated by Django 4.1.1 on 2023-05-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chall_name', models.CharField(max_length=200)),
                ('chall_type', models.CharField(max_length=200)),
                ('grade', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='qrcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('voice', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('letter_No', models.IntegerField()),
                ('correction', models.IntegerField()),
                ('chall_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qalamy.challenges')),
                ('child_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qalamy.child')),
            ],
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('voice', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('correction', models.IntegerField()),
                ('chall_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qalamy.challenges')),
                ('child_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qalamy.child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='parent_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qalamy.parents'),
        ),
        migrations.AddField(
            model_name='challenges',
            name='child_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qalamy.child'),
        ),
        migrations.AddField(
            model_name='challenges',
            name='parent_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qalamy.parents'),
        ),
    ]
