# Generated by Django 4.1.1 on 2023-05-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qalamy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='image',
            field=models.TextField(),
        ),
    ]
