# Generated by Django 4.1.1 on 2023-05-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qalamy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVoiceParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, upload_to='qrcodes/')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='challenges',
            name='parent_ID',
        ),
        migrations.RemoveField(
            model_name='letters',
            name='child_ID',
        ),
        migrations.RemoveField(
            model_name='letters',
            name='correction',
        ),
        migrations.RemoveField(
            model_name='myimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='words',
            name='child_ID',
        ),
        migrations.RemoveField(
            model_name='words',
            name='correction',
        ),
        migrations.AlterField(
            model_name='challenges',
            name='chall_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='chall_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='date',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='child',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='child',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='letters',
            name='text',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='letters',
            name='voice',
            field=models.FileField(blank=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='parents',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='parents',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='words',
            name='text',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='words',
            name='voice',
            field=models.FileField(blank=True, upload_to='qrcodes/'),
        ),
        migrations.CreateModel(
            name='WordsExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=200)),
                ('voice', models.FileField(blank=True, upload_to='qrcodes/')),
                ('image', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('letter_No', models.IntegerField()),
                ('challenges_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qalamy.challenges')),
            ],
        ),
        migrations.CreateModel(
            name='LettersExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=200)),
                ('voice', models.FileField(blank=True, upload_to='qrcodes/')),
                ('image', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('challenges_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qalamy.challenges')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.IntegerField()),
                ('words_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qalamy.wordsexam')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.IntegerField()),
                ('letter_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Qalamy.lettersexam')),
            ],
        ),
    ]
