# Generated by Django 4.1.1 on 2023-05-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qalamy', '0002_alter_myimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myimage',
            name='image',
        ),
    ]
