# Generated by Django 4.1.1 on 2023-05-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qalamy', '0003_remove_myimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, upload_to='audio/')),
            ],
        ),
    ]
