# Generated by Django 4.1.1 on 2023-05-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qalamy', '0005_alter_myaudio_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyAudio',
        ),
    ]
