# Generated by Django 4.1.1 on 2023-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qalamy', '0006_delete_myaudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyVoiceParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, upload_to='qrcodes/')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
    ]
